Repository griffithlab/civic-v2, pull requests merged in 2022-04, with the labels that each got.

#424 Fix up typos in analytics request tracking
  server/app/lib/graphql_analytics_tracer.rb
Labels: bugfix

#425 Correct links on data releases pages
  server/app/graphql/types/queries/data_release_query.rb
Labels: bugfix

#434 Fix nonworking flag ribbon link
  client/src/app/components/flags/flaggable/flaggable.module.ts
Labels: bug, bugfix

#432 Refactor gene revise form to use the new MutatorWithState
  client/src/app/forms/assertion-revise/assertion-revise.form.html
  client/src/app/forms/evidence-revise/evidence-revise.form.html
  client/src/app/forms/gene-revise/gene-revise.form.html
  client/src/app/forms/gene-revise/gene-revise.form.ts
  client/src/app/forms/gene-revise/gene-revise.module.ts
  client/src/app/forms/gene-revise/gene-revise.service.ts
  client/src/app/forms/variant-revise/variant-revise.form.html
  client/src/app/views/genes/genes-revise/genes-suggest/genes-suggest.page.html
Labels: enhancement

#436 refresh notifications and event feeds automatically in production mode
  client/src/app/components/events/event-feed/event-feed.component.ts
  client/src/app/components/layout/viewer-button/viewer-button.component.ts
  client/src/app/components/source-suggestions/source-suggestions-table/source-suggestions-table.component.html
Labels: enhancement

#437 Hide notification count badge when count is zero
  client/src/app/components/layout/viewer-button/viewer-button.component.html
Labels: bugfix

#450 Ensure that ready? on RejectRevision returns true at the end
  server/app/graphql/mutations/reject_revisions.rb
Labels: bugfix

#452 Remove auto-refresh from full activity feed
  client/src/app/components/events/event-feed/event-feed.component.ts
  client/src/app/components/events/homepage-event-feed/homepage-event-feed.component.html
  client/src/app/components/events/homepage-event-feed/homepage-event-feed.component.less
  client/src/app/components/events/homepage-event-feed/homepage-event-feed.component.ts
  client/src/app/components/events/homepage-event-feed/homepage-event-feed.module.ts
  client/src/app/views/curation/curation-activity/curation-timeline/curation-timeline.page.html
  client/src/app/views/welcome/welcome.component.html
  client/src/app/views/welcome/welcome.module.ts
Labels: bugfix

#454 Allow curating an EID from a source suggestion
  client/src/app/components/source-suggestions/source-suggestions-table/source-suggestions-table.component.html
  client/src/app/components/source-suggestions/source-suggestions-table/source-suggestions-table.module.ts
  client/src/app/forms/evidence-submit/evidence-submit.form.html
  client/src/app/forms/evidence-submit/evidence-submit.form.ts
  client/src/app/forms/evidence-submit/evidence-submit.query.gql
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.field-policies.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/resolvers/browse_source_suggestions.rb
  server/app/graphql/types/queries/source_queries.rb
  server/app/graphql/types/source_suggestion_values_type.rb
Labels: enhancement

#473 Include updated_at timestamp when calculating cache key for variants
  server/app/models/my_variant_info.rb
Labels: bugfix

#476 New popovers for flags and revisions
  client/src/app/components/flags/flag-popover/flag-popover.component.html
  client/src/app/components/flags/flag-popover/flag-popover.component.less
  client/src/app/components/flags/flag-popover/flag-popover.component.ts
  client/src/app/components/flags/flag-popover/flag-popover.module.ts
  client/src/app/components/flags/flag-popover/flag-popover.query.gql
  client/src/app/components/flags/flag-tag/flag-tag.component.html
  client/src/app/components/flags/flag-tag/flag-tag.component.ts
  client/src/app/components/flags/flag-tag/flag-tag.module.ts
  client/src/app/components/revisions/revision-popover/revision-popover.component.html
  client/src/app/components/revisions/revision-popover/revision-popover.component.less
  client/src/app/components/revisions/revision-popover/revision-popover.component.ts
  client/src/app/components/revisions/revision-popover/revision-popover.module.ts
  client/src/app/components/revisions/revision-popover/revision-popover.query.gql
  client/src/app/components/revisions/revision-tag/revision-tag.component.html
  client/src/app/components/revisions/revision-tag/revision-tag.module.ts
  client/src/app/generated/civic.apollo.ts
  server/app/models/flag.rb
Labels: enhancement

#479 Gracefully display revisions that point to deleted entities
  client/src/app/components/revisions/revision-list-diff/revision-list-diff.component.html
  client/src/app/components/revisions/revision-list-diff/revision-list-diff.module.ts
  client/src/app/components/revisions/revisions-list-and-filter/revisions-list-and-filter.query.gql
  client/src/app/core/pipes/camel-case-to-words-pipe.ts
  client/src/app/core/pipes/pipes.module.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.field-policies.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/types/revisions/linkout_data.rb
  server/app/graphql/types/revisions/moderated_field_type.rb
Labels: bugfix

#482 when there is no source citation, fall back on the name
  client/src/app/forms/config/types/source-input/source-selector/source-selector-typeahead/source-selector-typeahead.type.html
  client/src/app/forms/config/types/source-input/source-selector/source-selector-typeahead/source-selector-typeahead.type.ts
Labels: bugfix

#484 Turn aliases and hgvs descriptions into tag lists
  client/src/app/components/assertions/assertions-popover/assertion-popover.component.html
  client/src/app/components/assertions/assertions-popover/assertion-popover.query.gql
  client/src/app/components/assertions/assertions-popover/assertions-popover.module.ts
  client/src/app/components/drugs/cvc-drug-popover/cvc-drug-popover.component.html
  client/src/app/components/drugs/cvc-drug-popover/cvc-drug-popover.module.ts
  client/src/app/components/genes/gene-popover/gene-popover.component.html
  client/src/app/components/variants/variant-popover/variant-popover.component.html
  client/src/app/generated/civic.apollo.ts
  client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.module.ts
  client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.page.html
  client/src/app/views/drugs/drugs-detail/drugs-detail.component.html
  client/src/app/views/drugs/drugs-detail/drugs-detail.module.ts
  client/src/app/views/genes/genes-detail/genes-summary/genes-summary.module.ts
  client/src/app/views/genes/genes-detail/genes-summary/genes-summary.page.html
  client/src/app/views/variants/variants-detail/variants-summary/variants-summary.module.ts
  client/src/app/views/variants/variants-detail/variants-summary/variants-summary.page.html
Labels: enhancement

#483 Activity feed polls for new activity and will prompt a user to refresh if new events are found
  client/src/app/components/events/event-feed/event-feed.component.html
  client/src/app/components/events/event-feed/event-feed.component.ts
  client/src/app/components/events/event-feed/event-feed.gql
  client/src/app/components/events/event-feed/event-feed.module.ts
  client/src/app/generated/civic.apollo.ts
Labels: enhancement

#478 Create editor-facing "Add Variant" form.
  client/src/app/components/layout/viewer-button/viewer-button.component.html
  client/src/app/components/layout/viewer-button/viewer-button.component.ts
  client/src/app/components/layout/viewer-button/viewer-button.module.ts
  client/src/app/forms/assertion-revise/assertion-revise.module.ts
  client/src/app/forms/assertion-submit/assertion-submit.module.ts
  client/src/app/forms/config/types/cancel-button/cancel-button.type.html
  client/src/app/forms/config/types/cancel-button/cancel-button.type.ts
  client/src/app/forms/config/types/org-submit-button/org-submit-button.module.ts
  client/src/app/forms/config/types/org-submit-button/org-submit-button.type.html
  client/src/app/forms/config/types/org-submit-button/org-submit-button.type.less
  client/src/app/forms/config/types/org-submit-button/org-submit-button.type.ts
  client/src/app/forms/config/types/submit-button/submit-button.type.html
  client/src/app/forms/config/types/submit-button/submit-button.type.ts
  client/src/app/forms/config/types/variant-input/variant-input.query.gql
  client/src/app/forms/config/wrappers/form-container/form-container.wrapper.less
  client/src/app/forms/evidence-revise/evidence-revise.form.ts
  client/src/app/forms/evidence-revise/evidence-revise.module.ts
  client/src/app/forms/evidence-submit/evidence-submit.module.ts
  client/src/app/forms/gene-revise/gene-revise.module.ts
  client/src/app/forms/source-submit/source-submit.module.ts
  client/src/app/forms/variant-group-revise/variant-group-revise.module.ts
  client/src/app/forms/variant-group-submit/variant-group-submit.module.ts
  client/src/app/forms/variant-revise/variant-revise.module.ts
  client/src/app/forms/variant-submit/variant-submit.form.html
  client/src/app/forms/variant-submit/variant-submit.form.less
  client/src/app/forms/variant-submit/variant-submit.form.ts
  client/src/app/forms/variant-submit/variant-submit.module.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/views/variants/variants-home/variants-home.module.ts
  client/src/app/views/variants/variants-home/variants-home.page.html
  client/src/app/views/variants/variants-home/variants-home.page.less
  client/src/app/views/variants/variants-home/variants-home.page.ts
Labels: enhancement

#493 New endpoint for all genes (required for CIViCpy)
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/resolvers/top_level_genes.rb
  server/app/graphql/types/entities/variant_type.rb
  server/app/graphql/types/query_type.rb
Labels: enhancement

#500 Consistently disable nested tag popovers
  client/src/app/components/comments/comment-popover/comment-popover.component.html
  client/src/app/components/evidence/evidence-tag/evidence-tag.component.html
  client/src/app/components/flags/flag-popover/flag-popover.component.html
  client/src/app/components/organizations/organization-tag/organization-tag.component.html
  client/src/app/components/revisions/revision-popover/revision-popover.component.html
  client/src/app/components/variant-groups/variant-group-popover/variant-group-popover.component.html
Labels: bugfix

#499 Refresh revision lists and detail pages when revisions are proposed or accepted
  client/src/app/components/revisions/revision-list/revision-list.component.ts
  client/src/app/components/revisions/revisions-list-and-filter/revisions-list-and-filter.component.html
  client/src/app/components/revisions/revisions-list-and-filter/revisions-list-and-filter.component.ts
  client/src/app/forms/assertion-revise/assertion-revise.form.ts
  client/src/app/forms/evidence-revise/evidence-revise.form.ts
  client/src/app/forms/gene-revise/gene-revise.form.ts
  client/src/app/forms/variant-group-revise/variant-group-revise.form.ts
  client/src/app/forms/variant-revise/variant-revise.form.ts
Labels: bugfix

#498 Correct logic for users accepting their own revisions on genes/variants
  server/app/graphql/resolvers/validate_revisions_for_acceptance.rb
Labels: bugfix

#497 Include interaction type in list of fields
  server/app/models/actions/suggest_evidence_item_revision.rb
Labels: bugfix

#501 Begin porting scheduled tasks over to v2
  server/Gemfile
  server/Gemfile.lock
  server/app/jobs/allele_registry_ids.rb
  server/app/jobs/generate_monthly_tsvs.rb
  server/app/jobs/generate_nightly_tsvs.rb
  server/app/jobs/generate_tsvs.rb
  server/app/jobs/refresh_materialized_views.rb
  server/app/jobs/set_allele_registry_id_single_variant.rb
  server/app/lib/link_adaptors/base.rb
  server/app/models/variant.rb
  server/app/tsv_formatters/assertion_tsv_formatter.rb
  server/app/tsv_formatters/evidence_item_tsv_formatter.rb
  server/app/tsv_formatters/gene_tsv_formatter.rb
  server/app/tsv_formatters/variant_group_tsv_formatter.rb
  server/app/tsv_formatters/variant_tsv_formatter.rb
  server/config/initializers/sidekiq.rb
  server/config/scheduled_tasks.yml
  server/misc_scripts/add_allele_registry_link.rb
Labels: housekeeping

#505 replace favicon from yarn build with a different one if we're on staging
  .github/workflows/build_frontend.yml
  server/public/favicon.staging.ico
Labels: housekeeping

#507 Show reject button for users' own submissions, even if not an editor
  client/src/app/components/shared/moderate-entity-buttons/moderate-entity-button.ts
  client/src/app/components/shared/moderate-entity-buttons/moderate-entity-buttons.component.html
  client/src/app/generated/civic.apollo.ts
  client/src/app/views/assertions/assertions-detail/assertions-detail.query.gql
  client/src/app/views/assertions/assertions-detail/assertions-detail.view.html
  client/src/app/views/evidence/evidence-detail/evidence-detail.query.gql
  client/src/app/views/evidence/evidence-detail/evidence-detail.view.html
Labels: enhancement

#508 allow sorting by creation date in the source suggestion table
  client/src/app/components/source-suggestions/source-suggestions-table/source-suggestions-table.component.html
  client/src/app/components/source-suggestions/source-suggestions-table/source-suggestions-table.component.ts
  client/src/app/components/source-suggestions/source-suggestions-table/source-suggestions-table.query.gql
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.field-policies.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/resolvers/browse_source_suggestions.rb
  server/app/graphql/types/browse_tables/source_suggestions_sort_columns.rb
  server/app/graphql/types/entities/source_suggestion_type.rb
Labels: enhancement
