Repository griffithlab/civic-v2, pull requests merged in 2022-05, with the labels that each got.

#520 Add update task job files for allele registry
  server/app/jobs/allele_registry_ids.rb
  server/app/jobs/set_allele_registry_ids.rb
  server/app/jobs/update_allele_registry_ids.rb
  server/config/scheduled_tasks.yml
Labels: bugfix

#525 enable UI for sidekiq and cron jobs for admins
  client/proxy.config.json
  client/src/app/components/layout/viewer-button/viewer-button.component.html
  config/civic.conf
  server/Gemfile
  server/Gemfile.lock
  server/app/routing_constraints/user_logged_in_constraint.rb
  server/config/routes.rb
Labels: housekeeping

#523 Include suggeston count in source browse table
  client/src/app/components/sources/sources-table/sources-table.component.html
  client/src/app/components/sources/sources-table/sources-table.query.gql
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.field-policies.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/resolvers/browse_sources.rb
  server/app/graphql/types/browse_tables/browse_source_type.rb
  server/app/graphql/types/browse_tables/sources_sort_columns.rb
  server/app/graphql/types/entities/variant_type.rb
  server/app/jobs/refresh_materialized_views.rb
  server/db/migrate/20220505150407_update_source_browse_table_rows_to_version_4.rb
  server/db/migrate/20220511200531_update_source_browse_table_rows_to_version_5.rb
  server/db/schema.rb
  server/db/views/source_browse_table_rows_v04.sql
  server/db/views/source_browse_table_rows_v05.sql
Labels: enhancement

#527 Additional API updates needed for CIViCpy
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.field-policies.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/resolvers/top_level_evidence_items.rb
  server/app/graphql/types/query_type.rb
Labels: enhancement

#530 Improve form clarity when reparenting EIDs
  client/src/app/forms/config/types/variant-input/variant-input.module.ts
  client/src/app/forms/config/types/variant-input/variant-input.query.gql
  client/src/app/forms/config/types/variant-input/variant-input.type.html
  client/src/app/forms/evidence-revise/evidence-revise.form.ts
  client/src/app/forms/evidence-revise/evidence-revise.module.ts
  client/src/app/forms/evidence-revise/evidence-revise.query.gql
  client/src/app/generated/civic.apollo.ts
Labels: enhancement

#531 filter out civicbot events on homepage/main activity feed
  client/src/app/components/events/event-feed/event-feed.component.ts
  client/src/app/components/events/event-feed/event-feed.gql
  client/src/app/components/events/homepage-event-feed/homepage-event-feed.component.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  client/src/app/views/curation/curation-activity/curation-timeline/curation-timeline.page.html
  server/app/graphql/resolvers/top_level_events.rb
  server/app/models/constants.rb
Labels: housekeeping
