Repository griffithlab/civic-v2, pull requests merged in 2022-08, with the labels that each got.

#593 Display unregistered allele registry variants correctly
  client/src/app/components/variants/variant-popover/variant-popover.component.html
  client/src/app/views/variants/variants-detail/variants-summary/variants-summary.page.html
Labels: bugfix

#605 Make variant name search in browse table wildcard match in both directions
  server/app/graphql/resolvers/browse_variants.rb
Labels: bugfix

#604 Author list improvements for sources
  server/app/graphql/types/entities/source_type.rb
  server/app/models/source.rb
  server/db/migrate/20220816205024_update_source_browse_table_rows_to_version_6.rb
  server/db/schema.rb
  server/db/views/source_browse_table_rows_v06.sql
Labels: housekeeping

#606 Clicking a revision tag takes you to the the revision set regardless of status
  client/src/app/components/comments/comment-body/comment-body.component.html
  client/src/app/components/comments/comment-list/comment-list.query.gql
  client/src/app/components/events/event-feed/event-feed.gql
  client/src/app/components/events/event-timeline-item/event-timeline-item.component.html
  client/src/app/components/revisions/revision-tag/revision-tag.component.html
  client/src/app/components/revisions/revision-tag/revision-tag.component.ts
  client/src/app/components/revisions/revisions-list-and-filter/revisions-list-and-filter.component.html
  client/src/app/components/revisions/revisions-list-and-filter/revisions-list-and-filter.component.ts
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/types/commentable/comment_tag_segment.rb
  server/app/models/actions/extract_references.rb
  server/app/models/constants.rb
Labels: enhancement

#612 build client when tests are run
  .github/workflows/tests.yml
Labels: housekeeping

#610 Allow admins to set a parent organization when editing orgs in the admin UI
  server/Gemfile.lock
  server/app/admin/organizations_admin.rb
  server/app/models/organization.rb
Labels: enhancement
