Repository griffithlab/civic-v2, pull requests merged in 2023-08, with the labels that each got.

#860 Handle case when user is in multiple organizations but has not yet performed any actions
  client/src/app/forms2/types/org-submit-button/org-submit-button.type.html
  server/app/models/mane_select_transcript.rb
Labels: bugfix

#862 Show badge indicating number of comments on "Comments" tab nav
  client/src/app/components/shared/tab-navigation/tab-navigation.component.html
  client/src/app/components/shared/tab-navigation/tab-navigation.component.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/views/assertions/assertions-detail/assertions-detail.view.ts
  client/src/app/views/evidence/evidence-detail/evidence-detail.view.ts
  client/src/app/views/genes/genes-detail/genes-detail.view.ts
  client/src/app/views/molecular-profiles/molecular-profiles-detail/molecular-profiles-detail.view.ts
  client/src/app/views/sources/sources-detail/sources-detail.query.gql
  client/src/app/views/sources/sources-detail/sources-detail.view.html
  client/src/app/views/sources/sources-detail/sources-detail.view.ts
  client/src/app/views/variant-groups/variant-groups-detail/variant-groups-detail.view.ts
  client/src/app/views/variants/variants-detail/variants-detail.view.ts
  server/app/models/source.rb
Labels: enhancement

#864 Validate name uniqueness, but be aware of revision context
  server/app/models/actions/suggest_revision_set.rb
  server/app/models/concerns/moderated.rb
  server/app/models/molecular_profile.rb
  server/app/models/variant.rb
Labels: bugfix

#868 add user search in admin
  server/app/admin/users_admin.rb
Labels: new-feature

#869 Add hinting and validation for users entering their social media handles
  client/src/app/forms/user-profile/user-profile.form.html
  client/src/app/forms/user-profile/user-profile.module.ts
  server/app/graphql/mutations/edit_user.rb
  server/app/models/user.rb
Labels: enhancement

#870 new dev scripts to help keep civic-docs updated w/ client icon & model changes
  client/package.json
  client/scripts/generate-icon-data.js
  client/scripts/generate-icon-rst.js
  client/src/app/generated/civic-docs.aliases.rst
  client/src/app/generated/civic.docs-aliases.rst
  client/src/app/generated/civic.icons.data.json
  client/yarn.lock
Labels: enhancement

#878 Add disease search to admin
  server/app/admin/diseases_admin.rb
  server/app/admin/variants_admin.rb
Labels: enhancement

#879 update Rails version for security patches
  server/Gemfile.lock
Labels: housekeeping

#880 Add some very rudimentary API usage examples to the repo
  examples/fetch_acmg_code.R
  examples/fetch_all_variants.py
Labels: ignore-for-release

#881 Make Simple MPs inherit aliases from their Variant
  client/src/app/forms/molecular-profile-revise/molecular-profile-revise.queries.gql
  client/src/app/forms2/config/molecular-profile-revise/molecular-profile-revise.form.html
  client/src/app/forms2/config/molecular-profile-revise/molecular-profile-revise.form.ts
  client/src/app/forms2/config/molecular-profile-revise/molecular-profile-revise.query.gql
  client/src/app/forms2/types/tag-input/tag-input.type.html
  client/src/app/forms2/types/tag-input/tag-input.type.ts
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/types/entities/molecular_profile_type.rb
  server/app/models/actions/suggest_molecular_profile_revision.rb
  server/app/models/variant.rb
  server/misc_scripts/liftover_variant_aliases.rb
Labels: new-feature
