Repository griffithlab/civic-v2, pull requests merged in 2023-02, with the labels that each got.

#727 display molecular profile count on more popovers and tables
  client/src/app/components/genes/genes-table/genes-table.component.html
  client/src/app/components/genes/genes-table/genes-table.query.gql
  client/src/app/components/phenotypes/phenotype-popover/phenotype-popover.component.html
  client/src/app/components/phenotypes/phenotype-popover/phenotype-popover.query.gql
  client/src/app/components/therapies/cvc-therapy-popover/cvc-therapy-popover.component.html
  client/src/app/components/therapies/cvc-therapy-popover/cvc-therapy-popover.query.gql
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  client/yarn.lock
  server/Gemfile.lock
  server/app/graphql/resolvers/browse_genes.rb
  server/app/graphql/types/browse_tables/browse_gene_type.rb
  server/app/graphql/types/browse_tables/genes_sort_columns.rb
  server/app/graphql/types/popovers/phenotype_popover_type.rb
  server/app/graphql/types/popovers/therapy_popover_type.rb
  server/db/migrate/20230201205039_update_gene_browse_table_rows_to_version_6.rb
  server/db/schema.rb
  server/db/views/gene_browse_table_rows_v06.sql
Labels: housekeeping

#732 show OpenCRAVAT url on MP page Variant cards
  client/src/app/components/molecular-profiles/molecular-profile-variant-card/molecular-profile-variant-card.component.html
  client/src/app/components/molecular-profiles/molecular-profile-variant-card/molecular-profile-variant-card.module.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/views/molecular-profiles/molecular-profiles-detail/molecular-profiles-summary/molecular-profiles-summary.query.gql
Labels: enhancement

#742 Add creation comment to the revision popover
  client/src/app/components/revisions/revision-popover/revision-popover.component.html
  client/src/app/components/revisions/revision-popover/revision-popover.query.gql
  client/src/app/generated/civic.apollo.ts
Labels: enhancement

#741 Fix horizontal scrolling issues in various tables
  client/src/app/components/assertions/assertions-table/assertions-table.component.html
  client/src/app/components/molecular-profiles/molecular-profile-table/molecular-profile-table.component.html
Labels: bugfix

#740 Update formatting of MyGeneInfo Overview to avoid overlap on smaller screens
  client/src/app/components/genes/my-gene-info/my-gene-info.component.html
  client/src/app/components/genes/my-gene-info/my-gene-info.component.less
  client/src/app/components/genes/my-gene-info/my-gene-info.module.ts
Labels: bugfix

#739 Add MANE select transcript
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  client/src/app/views/variants/variants-detail/variants-summary/variants-summary.page.html
  client/src/app/views/variants/variants-detail/variants-summary/variants-summary.query.gql
  server/app/graphql/types/entities/variant_type.rb
  server/app/models/mane_select_transcript.rb
Labels: enhancement

#738 Lookup Variant by alias before creating a new one
  server/app/graphql/mutations/add_variant.rb
Labels: bugfix

#737 Remove nzLabel on the quicksearch dropdown options to remove tooltip
  client/src/app/components/layout/quicksearch/quicksearch-component.html
Labels: bugfix

#736 Fix flickering comment-popover
  client/src/app/components/comments/comment-popover/comment-popover.query.gql
  client/src/app/generated/civic.apollo.ts
Labels: bugfix

#735 Allow moving of variants between genes in variant revise form
  client/src/app/components/revisions/revision-list/revision-list.component.html
  client/src/app/components/revisions/revision-list/revision-list.module.ts
  client/src/app/forms/variant-revise/variant-revise.form.ts
  client/src/app/forms/variant-revise/variant-revise.module.ts
Labels: new-feature

#754 Handle cases where none of the allele registry transcripts are tagged as MANE select
  server/app/models/mane_select_transcript.rb
Labels: bugfix

#746 Handle revision popover for revisions without creation comment
  client/src/app/components/revisions/revision-popover/revision-popover.component.html
Labels: bugfix

#751 Long evidence and assertion descriptons will overflow into scroll
  client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.page.html
  client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.page.less
  client/src/app/views/evidence/evidence-detail/evidence-summary/evidence-summary.page.html
  client/src/app/views/evidence/evidence-detail/evidence-summary/evidence-summary.page.less
Labels: bugfix

#755 MyDisease.info integration
  client/src/app/components/diseases/my-disease-info/my-disease-info.component.html
  client/src/app/components/diseases/my-disease-info/my-disease-info.component.less
  client/src/app/components/diseases/my-disease-info/my-disease-info.component.ts
  client/src/app/components/diseases/my-disease-info/my-disease-info.module.ts
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  client/src/app/views/diseases/diseases-detail/diseases-summary/diseases-summary.component.html
  client/src/app/views/diseases/diseases-detail/diseases-summary/diseases-summary.component.ts
  client/src/app/views/diseases/diseases-detail/diseases-summary/diseases-summary.module.ts
  client/src/app/views/diseases/diseases-detail/diseases-summary/diseases-summary.query.gql
  server/app/graphql/types/entities/disease_type.rb
  server/app/graphql/types/entities/my_disease_info_type.rb
  server/app/models/my_disease_info.rb
Labels: new-feature
