Repository griffithlab/civic-v2, pull requests merged in 2023-03, with the labels that each got.

#758 Introduce Basic MyChem.info integration
  client/src/app/components/diseases/my-disease-info/my-disease-info.component.html
  client/src/app/components/therapies/my-chem-info/my-chem-info.component.html
  client/src/app/components/therapies/my-chem-info/my-chem-info.component.less
  client/src/app/components/therapies/my-chem-info/my-chem-info.component.ts
  client/src/app/components/therapies/my-chem-info/my-chem-info.module.ts
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  client/src/app/views/therapies/therapies-detail/therapies-summary/therapies-summary.component.html
  client/src/app/views/therapies/therapies-detail/therapies-summary/therapies-summary.module.ts
  client/src/app/views/therapies/therapies-detail/therapies-summary/therapies-summary.query.gql
  server/app/graphql/types/entities/my_chem_info_type.rb
  server/app/graphql/types/entities/my_disease_info_type.rb
  server/app/graphql/types/entities/therapy_type.rb
  server/app/models/my_chem_info.rb
  server/app/models/my_disease_info.rb
Labels: new-feature

#766 add entrez symbol filtering support for single gene query
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/types/query_type.rb
Labels: enhancement

#767 dont display a broken link when transcript is missing
  client/src/app/components/variants/coordinates-card/coordinates-card.component.html
Labels: bugfix

#768 add top bar link to docs
  client/src/app/layout/layout.component.html
Labels: enhancement

#771 predisposition icon loading, other icon issues fixed
  client/src/app/generated/civic.icons.ts
  client/src/app/icons-provider.module.ts
  client/src/assets/icons/attribute/mixed-outline.svg
  client/src/assets/icons/attribute/na-outline.svg
  client/src/assets/icons/attribute/neomorphic-outline.svg
  client/src/assets/icons/attribute/predisposition-outline.svg
  client/src/assets/icons/attribute/significanceunknown-outline.svg
  client/src/assets/icons/fullcolor/evidenceitem-fullcolor.svg
Labels: bugfix

#773 removed duplicate mission statement block; added breakpoint layouts
  client/src/app/views/pages/pages-about/pages-about.page.html
Labels: bugfix
