Repository griffithlab/civic-v2, pull requests merged in 2023-01, with the labels that each got.

#682 distinguish between false and undefined
  client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.page.html
Labels: bugfix

#694 Backend Field Renames
  client/src/app/components/revisions/revision-list/revision-list.component.html
  server/app/admin/variants_admin.rb
  server/app/graphql/resolvers/top_level_assertions.rb
  server/app/graphql/types/browse_tables/browse_source_type.rb
  server/app/graphql/types/entities/assertion_type.rb
  server/app/graphql/types/entities/variant_type.rb
  server/app/jobs/allele_registry_ids.rb
  server/app/lib/scrapers/asco.rb
  server/app/lib/scrapers/ash.rb
  server/app/lib/scrapers/pub_med.rb
  server/app/models/actions/suggest_assertion_revision.rb
  server/app/models/actions/suggest_variant_revision.rb
  server/app/models/assertion.rb
  server/app/models/hgvs_description.rb
  server/app/models/input_adaptors/assertion_input_adaptor.rb
  server/app/models/input_adaptors/variant_input_adaptor.rb
  server/app/models/my_variant_info.rb
  server/app/models/source.rb
  server/app/models/source_suggestion.rb
  server/app/models/variant.rb
  server/app/scrapers/asco.rb
  server/app/scrapers/pub_med.rb
  server/app/tsv_formatters/assertion_tsv_formatter.rb
  server/app/tsv_formatters/evidence_item_tsv_formatter.rb
  server/app/tsv_formatters/variant_tsv_formatter.rb
  server/app/validators/assertion_validator.rb
  server/db/migrate/20230110190854_rename_source_description.rb
  server/db/migrate/20230110191626_update_source_browse_table_rows_to_version_7.rb
  server/db/migrate/20230110192703_rename_assertion_columns.rb
  server/db/migrate/20230110201023_rename_hgvs_expression.rb
  server/db/migrate/20230110202136_update_hgvs_revisions.rb
  server/db/migrate/20230110203308_remove_unused_variant_columns.rb
  server/db/schema.rb
  server/db/views/source_browse_table_rows_v07.sql
  server/test/fixtures/variants.yml
Labels: housekeeping

#701 do not attempt to look for misspellings unless there are no matches
  server/app/graphql/resolvers/top_level_evidence_items.rb
Labels: bugfix

#700 Rename drugs to therapies on the backend.
  server/app/admin/assertions_admin.rb
  server/app/admin/evidence_items_admin.rb
  server/app/admin/therapies_admin.rb
  server/app/graphql/mutations/add_therapy.rb
  server/app/graphql/resolvers/browse_genes.rb
  server/app/graphql/resolvers/browse_molecular_profiles.rb
  server/app/graphql/resolvers/browse_variants.rb
  server/app/graphql/resolvers/top_level_assertions.rb
  server/app/graphql/resolvers/top_level_evidence_items.rb
  server/app/graphql/resolvers/top_level_therapies.rb
  server/app/graphql/types/browse_tables/browse_gene_type.rb
  server/app/graphql/types/browse_tables/browse_molecular_profile_type.rb
  server/app/graphql/types/browse_tables/browse_therapy_type.rb
  server/app/graphql/types/browse_tables/browse_variant_type.rb
  server/app/graphql/types/civic_timepoint_stats.rb
  server/app/graphql/types/entities/assertion_type.rb
  server/app/graphql/types/entities/evidence_item_type.rb
  server/app/graphql/types/entities/therapy_type.rb
  server/app/graphql/types/popovers/therapy_popover_type.rb
  server/app/graphql/types/queries/typeahead_queries.rb
  server/app/graphql/types/query_type.rb
  server/app/lib/importer/nci_thesaurus_mirror.rb
  server/app/lib/link_adaptors/therapy.rb
  server/app/models/actions/suggest_assertion_revision.rb
  server/app/models/actions/suggest_evidence_item_revision.rb
  server/app/models/assertion.rb
  server/app/models/civic_stats.rb
  server/app/models/constants.rb
  server/app/models/drug_alias.rb
  server/app/models/evidence_item.rb
  server/app/models/frontend_router.rb
  server/app/models/input_adaptors/assertion_input_adaptor.rb
  server/app/models/input_adaptors/evidence_item_input_adaptor.rb
  server/app/models/therapy.rb
  server/app/models/therapy_alias.rb
  server/app/tsv_formatters/assertion_tsv_formatter.rb
  server/app/tsv_formatters/evidence_item_tsv_formatter.rb
  server/app/validators/assertion_validator.rb
  server/app/validators/evidence_item_validator.rb
  server/db/migrate/20230111182847_rename_drugs_to_therapies.rb
  server/db/migrate/20230113161230_update_variant_browse_table_rows_to_version_9.rb
  server/db/migrate/20230113161603_update_molecular_profile_browse_table_rows_to_version_8.rb
  server/db/migrate/20230113161807_update_gene_browse_table_rows_to_version_4.rb
  server/db/schema.rb
  server/db/views/gene_browse_table_rows_v04.sql
  server/db/views/molecular_profile_browse_table_rows_v08.sql
  server/db/views/variant_browse_table_rows_v09.sql
Labels: housekeeping

#702 Scrape abstract text for ASH sources
  server/app/lib/scrapers/ash.rb
  server/app/lib/scrapers/ash_record_response.rb
  server/db/migrate/20230113171643_backfill_ash.rb
  server/db/schema.rb
Labels: enhancement

#703 Browse table updates
  client/src/app/components/molecular-profiles/molecular-profile-table/molecular-profile-table.component.html
  client/src/app/components/molecular-profiles/molecular-profile-table/molecular-profile-table.component.ts
  client/src/app/components/molecular-profiles/molecular-profile-table/molecular-profile-table.query.gql
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/resolvers/browse_molecular_profiles.rb
  server/app/graphql/types/browse_tables/browse_molecular_profile_type.rb
  server/app/graphql/types/browse_tables/molecular_profiles_sort_columns.rb
  server/db/migrate/20230113165605_update_molecular_profile_browse_table_rows_to_version_9.rb
  server/db/views/molecular_profile_browse_table_rows_v09.sql
Labels: enhancement

#704 Accomodate Leading Zeroes in DOID entry
  client/src/app/forms/config/types/disease-input/disease-input.query.gql
  client/src/app/forms/config/types/disease-input/disease-input.type.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/mutations/add_disease.rb
Labels: bugfix

#706 Update materialized views to use MP connections and remove variant_id and gene_id tables on eids and assertions
  server/app/models/assertion.rb
  server/app/models/evidence_item.rb
  server/app/models/gene.rb
  server/app/models/variant.rb
  server/db/migrate/20230113191354_update_variant_browse_table_rows_to_version_10.rb
  server/db/migrate/20230113193451_update_gene_browse_table_rows_to_version_5.rb
  server/db/schema.rb
  server/db/views/gene_browse_table_rows_v05.sql
  server/db/views/variant_browse_table_rows_v10.sql
Labels: enhancement

#708 Validate Citation ID formatting
  server/app/graphql/types/queries/source_queries.rb
  server/app/models/source.rb
Labels: bugfix

#707 Show all MPs unless deprecated in browse views. Show all sources in Source browse view
  client/src/app/components/molecular-profiles/molecular-profiles-menu/molecular-profiles-menu.component.ts
  server/app/models/advanced_searches/gene.rb
  server/app/models/gene.rb
  server/db/migrate/20230113204026_update_molecular_profile_browse_table_rows_to_version_10.rb
  server/db/migrate/20230113204556_update_source_browse_table_rows_to_version_9.rb
  server/db/schema.rb
  server/db/views/molecular_profile_browse_table_rows_v10.sql
  server/db/views/source_browse_table_rows_v09.sql
Labels: enhancement

#711 Remove variant_id on evidence item
  server/app/admin/assertions_admin.rb
  server/app/admin/evidence_items_admin.rb
  server/app/models/evidence_item.rb
  server/db/migrate/20230118154455_update_variant_browse_table_rows_to_version_11.rb
  server/db/migrate/20230118160302_drop_evidence_browse_table_rows_view.rb
  server/db/migrate/20230118160510_update_variant_group_browse_table_rows_to_version_2.rb
  server/db/migrate/20230118160944_update_disease_browse_table_rows_to_version_4.rb
  server/db/migrate/20230118161602_remove_variant_id_from_evidence_item.rb
  server/db/schema.rb
  server/db/views/disease_browse_table_rows_v04.sql
  server/db/views/variant_browse_table_rows_v11.sql
  server/db/views/variant_group_browse_table_rows_v02.sql
Labels: housekeeping

#718 Add Variant Type filtering and configurable page sizes to Variant Menu
  client/src/app/components/diseases/cvc-disease-popover/cvc-disease-popover.component.html
  client/src/app/components/diseases/cvc-disease-popover/cvc-disease-popover.query.gql
  client/src/app/components/molecular-profiles/molecular-profiles-menu/molecular-profiles-menu.component.html
  client/src/app/components/molecular-profiles/molecular-profiles-menu/molecular-profiles-menu.component.ts
  client/src/app/components/molecular-profiles/molecular-profiles-menu/molecular-profiles-menu.module.ts
  client/src/app/components/shared/tag-overflow/tag-overflow.component.html
  client/src/app/components/shared/tag-overflow/tag-overflow.component.ts
  client/src/app/components/shared/tag-overflow/tag-overflow.module.ts
  client/src/app/components/variants/variants-menu/variants-menu.component.html
  client/src/app/components/variants/variants-menu/variants-menu.component.ts
  client/src/app/components/variants/variants-menu/variants-menu.gql
  client/src/app/components/variants/variants-menu/variants-menu.module.ts
  client/src/app/components/variants/variants-table/variants-table.component.html
  client/src/app/components/variants/variants-table/variants-table.component.ts
  client/src/app/components/variants/variants-table/variants-table.query.gql
  client/src/app/core/pipes/event-verbiage-pipe.ts
  client/src/app/core/pipes/preposition-for-subject-pipe.ts
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  client/src/app/views/molecular-profiles/molecular-profiles-detail/molecular-profiles-summary/molecular-profiles-summary.query.gql
  server/app/graphql/resolvers/browse_variants.rb
  server/app/graphql/resolvers/top_level_variant_types.rb
  server/app/graphql/resolvers/top_level_variants.rb
  server/app/graphql/types/browse_tables/browse_variant_type.rb
  server/app/graphql/types/popovers/disease_popover_type.rb
  server/app/graphql/types/query_type.rb
  server/app/models/actions/create_complex_molecular_profile.rb
  server/db/migrate/20230120161541_update_variant_browse_table_rows_to_version_12.rb
  server/db/schema.rb
  server/db/views/variant_browse_table_rows_v12.sql
Labels: enhancement

#722 Fix a few more places where we were using the eid -> variant association
  server/app/graphql/resolvers/top_level_assertions.rb
  server/app/graphql/resolvers/top_level_evidence_items.rb
  server/app/graphql/resolvers/top_level_genes.rb
Labels: bugfix

#725 convert zero to one based coords in opencravat links
  server/app/jobs/generate_open_cravat_link.rb
  server/app/models/variant.rb
Labels: bugfix
