Repository griffithlab/civic-v2, pull requests merged in 2023-10, with the labels that each got.

#898 Updated news items with latest items, refactored news item list
  client/src/app/views/pages/pages-about/pages-about.page.ts
  client/src/app/views/welcome/news-item-list/news-item-list.component.html
  client/src/app/views/welcome/news-item-list/news-item-list.component.less
  client/src/app/views/welcome/news-item-list/news-item-list.component.ts
  client/src/app/views/welcome/welcome.component.html
  client/src/app/views/welcome/welcome.component.ts
  client/src/app/views/welcome/welcome.module.ts
  client/src/assets/images/2023-CGC-hackathon-attendees.jpg
Labels: housekeeping

#901 add ability to fetch Variants and MPs using ClinGen Allele Registry ids
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/mutations/create_molecular_profile.rb
  server/app/graphql/resolvers/top_level_molecular_profiles.rb
  server/app/graphql/resolvers/top_level_variants.rb
Labels: enhancement

#904 small admin fixes: display error message on duplicate ncit ids, add search
  server/app/admin/therapies_admin.rb
  server/app/models/therapy.rb
Labels: bugfix

#909 hotfix for variant-submit form
  client/src/app/forms/variant-submit/variant-submit.form.html
  client/src/app/forms/variant-submit/variant-submit.form.less
  client/src/app/forms/variant-submit/variant-submit.form.ts
  client/src/app/forms/variant-submit/variant-submit.module.ts
Labels: bugfix

#917 fix welcome page news item text
  client/src/app/views/welcome/welcome.component.ts
Labels: ignore-for-release

#907 do not force variant aliases to be all caps
  server/app/models/variant_alias.rb
Labels: bugfix

#913 Set allele_registry_id to None if the coordinates no longer resolve
  server/app/jobs/set_allele_registry_id_single_variant.rb
  server/app/jobs/set_allele_registry_ids.rb
  server/app/jobs/update_allele_registry_ids.rb
Labels: bugfix

#918 Fix COSMIC linkouts
  client/src/app/components/variants/my-variant-info/my-variant-info.component.html
Labels: bugfix

#920 Exclude EID to be revised from duplication check
  server/app/graphql/mutations/suggest_evidence_item_revision.rb
  server/app/models/input_adaptors/evidence_item_input_adaptor.rb
Labels: bugfix

#908 Flag Variants that resolve to identical allele registry IDs
  server/app/jobs/flag_duplicate_allele_registry_ids.rb
  server/config/scheduled_tasks.yml
Labels: enhancement

#905 Update how Source citation is constructed and information displayed on detail pages and in popovers
  client/src/app/components/sources/source-popover/source-popover.component.html
  client/src/app/components/sources/source-popover/source-popover.query.gql
  client/src/app/generated/civic.apollo.ts
  client/src/app/views/sources/sources-detail/sources-summary/sources-summary.page.html
  client/src/app/views/sources/sources-detail/sources-summary/sources-summary.query.gql
  server/app/lib/scrapers/asco_query_response.rb
  server/app/lib/scrapers/ash_record_response.rb
  server/app/lib/scrapers/pub_med_response.rb
  server/app/scrapers/asco_query_response.rb
  server/app/scrapers/pub_med_response.rb
Labels: enhancement

#921 restored missing forms gql files
  client/src/app/forms/config/assertion-revise/assertion-revise.query.gql
  client/src/app/forms/config/assertion-submit/assertion-submit.query.gql
  client/src/app/forms/config/evidence-revise/evidence-revise.form.ts
  client/src/app/forms/config/evidence-revise/evidence-revise.query.gql
  client/src/app/forms/config/evidence-submit/evidence-submit.form.ts
  client/src/app/forms/config/evidence-submit/evidence-submit.query.gql
  client/src/app/forms/config/variantgroup-revise/variantgroup-revise.form.ts
  client/src/app/forms/config/variantgroup-revise/variantgroup-revise.query.gql
  client/src/app/forms/config/variantgroup-submit/variantgroup-submit.query.gql
  client/src/app/forms/types/variant-select/variant-quick-add/variant-quick-add.query.gql
  client/src/app/forms/utilities/variant-group-to-model-fields.ts
  client/src/app/generated/civic.apollo.ts
Labels: bugfix

#883 Allow Sources to be marked as "fully curated" and display appropriate warnings throughout app
  client/src/app/forms/config/evidence-submit/evidence-submit.form.html
  client/src/app/forms/config/evidence-submit/evidence-submit.form.ts
  client/src/app/forms/config/evidence-submit/existing-evidence-count.gql
  client/src/app/forms/config/source-submit/source-submit.form.html
  client/src/app/forms/config/source-submit/source-submit.form.module.ts
  client/src/app/forms/config/source-submit/source-submit.form.ts
  client/src/app/forms/config/source-submit/source-submit.query.gql
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  client/src/app/views/sources/sources-detail/sources-detail.module.ts
  client/src/app/views/sources/sources-detail/sources-detail.query.gql
  client/src/app/views/sources/sources-detail/sources-detail.view.html
  server/app/graphql/types/entities/source_type.rb
  server/db/migrate/20230831142739_source_status.rb
  server/db/schema.rb
Labels: new-feature

#924 Allow disease and therapies to be deprecated and exclude those from views and typeaheads
  server/app/admin/diseases_admin.rb
  server/app/admin/therapies_admin.rb
  server/app/graphql/resolvers/top_level_therapies.rb
  server/app/graphql/types/queries/typeahead_queries.rb
  server/app/models/disease.rb
  server/app/models/therapy.rb
  server/app/validators/deprecation_validator.rb
  server/db/migrate/20231024150741_add_deprecate_column_to_diseases.rb
  server/db/migrate/20231024151822_add_deprecate_column_to_therapy.rb
  server/db/migrate/20231024153516_update_disease_browse_table_rows_to_version_5.rb
  server/db/schema.rb
  server/db/views/disease_browse_table_rows_v05.sql
Labels: enhancement

#922 Store and display last updated timestamp on materialized views
  client/src/app/components/diseases/diseases-table/diseases-table.query.gql
  client/src/app/components/genes/genes-table/genes-table.query.gql
  client/src/app/components/molecular-profiles/molecular-profile-table/molecular-profile-table.query.gql
  client/src/app/components/shared/table-counts/table-counts.component.html
  client/src/app/components/shared/table-counts/table-counts.component.ts
  client/src/app/components/shared/table-counts/table-counts.module.ts
  client/src/app/components/sources/sources-table/sources-table.query.gql
  client/src/app/components/variant-groups/variant-groups-table/variant-groups-table.query.gql
  client/src/app/components/variants/variants-table/variants-table.query.gql
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/resolvers/browse_diseases.rb
  server/app/graphql/resolvers/browse_genes.rb
  server/app/graphql/resolvers/browse_molecular_profiles.rb
  server/app/graphql/resolvers/browse_sources.rb
  server/app/graphql/resolvers/browse_variant_groups.rb
  server/app/graphql/resolvers/browse_variants.rb
  server/app/graphql/types/connections/browse_table_connection.rb
  server/app/jobs/refresh_materialized_views.rb
  server/app/jobs/refresh_single_view.rb
  server/app/models/disease_browse_table_row.rb
  server/app/models/gene_browse_table_row.rb
  server/app/models/materialized_views/disease_browse_table_row.rb
  server/app/models/materialized_views/gene_browse_table_row.rb
  server/app/models/materialized_views/materialized_view.rb
  server/app/models/materialized_views/molecular_profile_browse_table_row.rb
  server/app/models/materialized_views/source_browse_table_row.rb
  server/app/models/materialized_views/variant_browse_table_row.rb
  server/app/models/materialized_views/variant_group_browse_table_row.rb
  server/app/models/materialized_views/view_last_updated_timestamp.rb
  server/app/models/molecular_profile.rb
  server/app/models/molecular_profile_browse_table_row.rb
  server/app/models/source.rb
  server/app/models/source_browse_table_row.rb
  server/app/models/variant.rb
  server/app/models/variant_browse_table_row.rb
  server/app/models/variant_group_browse_table_row.rb
  server/db/migrate/20231023153037_add_last_updated_timestamps.rb
  server/db/schema.rb
Labels: enhancement

#925 clear comment after revision accept/reject succeeds
  client/src/app/components/revisions/revision-list/revision-list.component.ts
Labels: bugfix

#929 Various admin fixes
  server/app/admin/diseases_admin.rb
  server/app/admin/events_admin.rb
  server/app/admin/revisions_admin.rb
  server/app/admin/therapies_admin.rb
  server/app/admin/variants_admin.rb
Labels: bugfix

#930 include variants with no eids as long as they are not deprecated
  server/db/migrate/20231027155450_update_variant_browse_table_rows_to_version_13.rb
  server/db/schema.rb
  server/db/views/variant_browse_table_rows_v13.sql
Labels: enhancement
