Repository griffithlab/civic-v2, pull requests merged in 2023-04, with the labels that each got.

#774 add additional validations to prevent duplicate names on variants and molecular profiles
  server/app/models/molecular_profile.rb
  server/app/models/variant.rb
Labels: housekeeping

#777 Fixes [N/A N/A] attribute tag display issue
  client/.prettierrc.json
  client/src/app/components/shared/empty-value/empty-value.component.html
  client/src/app/components/shared/empty-value/empty-value.component.less
  client/src/app/components/shared/empty-value/empty-value.component.ts
  client/src/app/components/shared/empty-value/empty-value.module.ts
  client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.module.ts
  client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.page.html
  client/src/app/views/evidence/evidence-detail/evidence-summary/evidence-summary.module.ts
  client/src/app/views/evidence/evidence-detail/evidence-summary/evidence-summary.page.html
  client/src/app/views/molecular-profiles/molecular-profiles-detail/molecular-profiles-summary/molecular-profiles-summary.module.ts
  client/src/app/views/molecular-profiles/molecular-profiles-detail/molecular-profiles-summary/molecular-profiles-summary.page.html
Labels: bugfix

#778 Fixes for NCCN version and guideline field
  client/src/app/forms/config/types/nccn-guideline-input/nccn-guideline-input.type.html
  client/src/app/forms/config/types/nccn-version-input/nccn-version-input.type.ts
Labels: bugfix

#781 Minor source browse table improvements
  client/src/app/components/sources/sources-table/sources-table.component.html
  client/src/app/components/sources/sources-table/sources-table.query.gql
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/resolvers/browse_sources.rb
  server/app/graphql/types/browse_tables/browse_source_type.rb
  server/app/graphql/types/entities/source_type.rb
  server/db/migrate/20230410183404_update_source_browse_table_rows_to_version_10.rb
  server/db/schema.rb
  server/db/views/source_browse_table_rows_v10.sql
Labels: enhancement

#801 adds aliases col to variant-select's manager table
  client/src/app/forms2/types/evidence-select/evidence-manager/evidence-manager.component.html
  client/src/app/forms2/types/variant-select/variant-manager/variant-manager.component.html
  client/src/app/forms2/types/variant-select/variant-manager/variant-manager.component.less
  client/src/app/forms2/types/variant-select/variant-manager/variant-manager.config.ts
  client/src/app/forms2/types/variant-select/variant-manager/variant-manager.types.ts
  client/src/app/forms2/types/variant-select/variant-select.type.ts
Labels: bugfix

#802 fixes evidence/variant managers' tag popovers
  client/src/app/forms2/components/entity-tag-popover/entity-tag-popover.component.html
  client/src/app/forms2/components/entity-tag-popover/entity-tag-popover.component.ts
  client/src/app/forms2/components/entity-tag-popover/entity-tag-popover.module.ts
  client/src/app/forms2/types/evidence-select/evidence-select.type.ts
Labels: bugfix

#805 evidence/variant manager filter inputs no longer affected by parent select validation state
  client/src/app/forms2/types/evidence-select/evidence-manager/table-filter-input/table-filter-input.component.less
  client/src/app/forms2/types/variant-select/variant-select.type.less
Labels: bugfix

#812 entity-select dropdowns now limited to select width
  client/src/app/forms2/components/entity-select/entity-select.component.html
  client/src/app/forms2/types/disease-select/disease-select.type.html
  client/src/app/forms2/types/gene-select/gene-select.type.html
  client/src/app/forms2/types/therapy-select/therapy-select.type.html
  client/src/app/forms2/types/variant-select/variant-select.type.html
Labels: bugfix

#813 mp-editor's 'Add MP' button no longer wraps in narrow width layouts
  client/src/app/forms2/types/molecular-profile-select/molecular-profile-select.type.ts
  client/src/app/forms2/types/molecular-profile-select/mp-expression-editor/mp-expression-editor.component.html
  client/src/app/forms2/types/molecular-profile-select/mp-expression-editor/mp-expression-editor.component.less
Labels: bugfix

#815 molecular-profile select field UX improvements
  client/src/app/forms2/types/molecular-profile-select/molecular-profile-select.type.html
Labels: bugfix
