Repository griffithlab/civic-v2, pull requests merged in 2023-12, with the labels that each got.

#933 form field status display improved
  client/src/app/forms/config/evidence-revise/evidence-revise.form.config.ts
  client/src/app/forms/config/evidence-submit/evidence-submit.form.config.ts
  client/src/app/forms/mixins/entity-select-field.mixin.ts
  client/src/app/forms/test-pages/layout-tests/horizontal-form/horizontal-form.page.html
  client/src/app/forms/test-pages/layout-tests/inline-form/inline-form.page.html
  client/src/app/forms/types/direction-select/direction-select.type.ts
  client/src/app/forms/types/disease-select/disease-select.type.ts
  client/src/app/forms/types/interaction-select/interaction-select.type.ts
  client/src/app/forms/types/level-select/level-select.type.ts
  client/src/app/forms/types/molecular-profile-select/molecular-profile-select.type.ts
  client/src/app/forms/types/molecular-profile-select/mp-finder/mp-finder.component.html
  client/src/app/forms/types/molecular-profile-select/mp-finder/mp-finder.component.ts
  client/src/app/forms/types/origin-select/origin-select.type.ts
  client/src/app/forms/types/rating/rating.type.html
  client/src/app/forms/types/rating/rating.type.less
  client/src/app/forms/types/rating/rating.type.ts
  client/src/app/forms/types/significance-select/significance-select.type.ts
  client/src/app/forms/types/type-select/type-select.type.ts
  client/src/app/forms/wrappers/form-field/form-field.wrapper.html
  client/src/app/forms/wrappers/form-field/form-field.wrapper.less
  client/src/app/forms/wrappers/form-field/form-field.wrapper.ts
  client/src/app/layout/layout-routing.module.ts
  client/src/themes/default.less
  client/src/themes/global-variables.less
Labels: enhancement

#955 Add evidence_items_by_type counts to molecular profiles
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/types/entities/molecular_profile_type.rb
  server/app/graphql/types/molecular_profile/evidence_items_by_type_type.rb
  server/app/models/molecular_profile.rb
  server/db/migrate/20231122204214_create_evidence_items_by_types.rb
  server/db/schema.rb
  server/db/views/evidence_items_by_types_v01.sql
Labels: enhancement

#957 Fix how complex MPs are being determined
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/types/entities/molecular_profile_type.rb
  server/app/models/molecular_profile.rb
  server/app/validators/assertion_validator.rb
  server/app/validators/evidence_item_validator.rb
Labels: bugfix

#958 Fix small bugs with variant and mp deprecation
  client/src/app/forms/components/complex-molecular-profile-deprecate/complex-molecular-profile-deprecate.form.html
  client/src/app/forms/components/complex-molecular-profile-deprecate/complex-molecular-profile-deprecate.form.ts
  server/app/models/actions/deprecate_variant.rb
Labels: bugfix

#959 Fix variant creation success message.
  client/src/app/forms/config/variant-submit/variant-submit.form.html
  client/src/app/forms/config/variant-submit/variant-submit.form.ts
  client/src/app/forms/types/variant-select/variant-quick-add/variant-quick-add.form.ts
  client/src/app/forms/types/variant-select/variant-select.type.html
  client/src/app/forms/types/variant-select/variant-select.type.ts
Labels: bugfix

#961 client apollo codegen service components have updates
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
Labels: bugfix

#962 entity-select fields now display proper status on init
  client/src/app/forms/config/assertion-submit/assertion-submit.form.config.ts
  client/src/app/forms/mixins/entity-select-field.mixin.ts
Labels: bugfix

#964 Add missing model file
  server/app/models/evidence_items_by_type.rb
Labels: ignore-for-release

#965 fix unknown icon error in event-feed
  client/src/app/core/pipes/icon-name-for-event-action-pipe.ts
Labels: bugfix

#969 Fix variant quick add not working
  client/src/app/forms/types/variant-select/variant-quick-add/variant-quick-add.form.ts
Labels: bugfix

#970 Update DGIdb linkouts to work with v5
  client/src/app/views/genes/genes-detail/genes-summary/genes-summary.page.html
Labels: housekeeping
