Repository griffithlab/civic-v2, pull requests merged in 2023-11, with the labels that each got.

#934 fix event-feed sidebar list title
  client/src/app/components/events/event-feed/event-feed.component.html
Labels: bugfix

#939 fix hash completion in comment typeahead
  server/app/models/actions/extract_references.rb
Labels: bugfix

#932 When using the allele_registry permalink format, don't return deprecated variants
  server/app/models/frontend_router.rb
Labels: bugfix

#944 Fix variable name typo in therapy typeahead
  server/app/graphql/types/queries/typeahead_queries.rb
  server/app/models/therapy.rb
Labels: bugfix

#948 add filters for Entrez Symbol and IDs on the genes query
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/resolvers/top_level_genes.rb
Labels: new-feature

#712 Add event for variant creation
  client/src/app/core/pipes/event-verbiage-pipe.ts
  client/src/app/core/pipes/icon-name-for-event-action-pipe.ts
  client/src/app/forms/types/variant-select/variant-quick-add/variant-quick-add.form.html
  client/src/app/forms/types/variant-select/variant-quick-add/variant-quick-add.form.ts
  client/src/app/forms/types/variant-select/variant-quick-add/variant-quick-add.query.gql
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/civic.possible-types.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  client/src/app/views/variants/variants-detail/variants-summary/variants-summary.module.ts
  client/src/app/views/variants/variants-detail/variants-summary/variants-summary.page.html
  client/src/app/views/variants/variants-detail/variants-summary/variants-summary.query.gql
  server/app/graphql/mutations/create_variant.rb
  server/app/graphql/types/activities/create_variant_activity_type.rb
  server/app/graphql/types/activities/deprecate_variant_activity_type.rb
  server/app/graphql/types/entities/variant_type.rb
  server/app/graphql/types/events/event_action_type.rb
  server/app/graphql/types/interfaces/activity_interface.rb
  server/app/graphql/types/mutation_type.rb
  server/app/models/actions/create_variant.rb
  server/app/models/activities/base.rb
  server/app/models/activities/create_variant.rb
  server/app/models/create_variant_activity.rb
  server/app/models/variant.rb
  server/misc_scripts/backfill_variant_creation_event.rb
Labels: new-feature

#949 Add activity for complex MP creation
  client/src/app/core/pipes/event-verbiage-pipe.ts
  client/src/app/forms/types/molecular-profile-select/mp-expression-editor/mp-expression-editor.component.ts
  client/src/app/forms/types/molecular-profile-select/mp-expression-editor/mp-expression-editor.query.gql
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/civic.possible-types.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  client/src/app/views/molecular-profiles/molecular-profiles-detail/molecular-profiles-summary/molecular-profiles-summary.page.html
  client/src/app/views/molecular-profiles/molecular-profiles-detail/molecular-profiles-summary/molecular-profiles-summary.query.gql
  server/app/graphql/mutations/create_molecular_profile.rb
  server/app/graphql/types/activities/create_complex_molecular_profile_activity_type.rb
  server/app/graphql/types/entities/molecular_profile_type.rb
  server/app/graphql/types/events/event_action_type.rb
  server/app/models/actions/create_complex_molecular_profile.rb
  server/app/models/activities/create_complex_molecular_profile.rb
  server/app/models/create_complex_molecular_profile_activity.rb
  server/app/models/molecular_profile.rb
  server/misc_scripts/backfill_complex_mp_creation_event.rb
Labels: enhancement

#951 Add ability to deprecate complex molecular profiles directly
  client/src/app/forms/components/complex-molecular-profile-deprecate/complex-molecular-profile-deprecate.form.html
  client/src/app/forms/components/complex-molecular-profile-deprecate/complex-molecular-profile-deprecate.form.ts
  client/src/app/forms/components/complex-molecular-profile-deprecate/complex-molecular-profile-deprecate.module.ts
  client/src/app/forms/components/complex-molecular-profile-deprecate/complex-molecular-profile-deprecate.query.gql
  client/src/app/forms/components/variant-deprecate/variant-deprecate.form.ts
  client/src/app/forms/components/variant-deprecate/variant-deprecate.query.gql
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/civic.possible-types.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  client/src/app/views/molecular-profiles/molecular-profiles-detail/molecular-profiles-detail.module.ts
  client/src/app/views/molecular-profiles/molecular-profiles-detail/molecular-profiles-detail.query.gql
  client/src/app/views/molecular-profiles/molecular-profiles-detail/molecular-profiles-detail.view.html
  client/src/app/views/molecular-profiles/molecular-profiles-detail/molecular-profiles-summary/molecular-profiles-summary.page.html
  client/src/app/views/molecular-profiles/molecular-profiles-detail/molecular-profiles-summary/molecular-profiles-summary.query.gql
  server/app/graphql/mutations/deprecate_complex_molecular_profile.rb
  server/app/graphql/mutations/deprecate_variant.rb
  server/app/graphql/types/activities/deprecate_complex_molecular_profile_activity_type.rb
  server/app/graphql/types/entities/molecular_profile_type.rb
  server/app/graphql/types/entities/variant_type.rb
  server/app/graphql/types/interfaces/activity_interface.rb
  server/app/graphql/types/molecular_profile_deprecation_reason_mutation_input_type.rb
  server/app/graphql/types/molecular_profile_deprecation_reason_type.rb
  server/app/graphql/types/mutation_type.rb
  server/app/graphql/types/variant_deprecation_reason_type.rb
  server/app/models/actions/deprecate_complex_molecular_profile.rb
  server/app/models/actions/deprecate_variant.rb
  server/app/models/activities/deprecate_complex_molecular_profile.rb
  server/app/models/deprecate_complex_molecular_profile_activity.rb
  server/app/models/molecular_profile.rb
  server/db/migrate/20231116184536_add_deprecation_reason_column_to_mps.rb
  server/db/schema.rb
Labels: new-feature

#950 Fix molecular profile browse table formatting issue
  client/src/app/components/molecular-profiles/molecular-profile-table/molecular-profile-table.component.html
Labels: bugfix
