Repository griffithlab/civic-v2, pull requests merged in 2024-08, with the labels that each got.

#1085 Update mygene.info call to use v3 of the api
  server/app/models/my_gene_info.rb
Labels: bugfix

#1086 Fix formatting of NCIt Code and Alias search results in therapy typeahead
  client/src/app/forms/types/therapy-select/therapy-select.type.html
Labels: bugfix

#1083 Add full name to feature browse table
  client/src/app/components/features/features-table/features-table.component.html
  client/src/app/components/features/features-table/features-table.component.ts
  client/src/app/components/features/features-table/features-table.query.gql
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/resolvers/browse_features.rb
  server/app/graphql/types/browse_tables/browse_feature_type.rb
  server/app/graphql/types/browse_tables/features_sort_columns.rb
  server/app/models/feature.rb
  server/db/migrate/20240726163525_update_feature_browse_table_rows_to_version_6.rb
  server/db/schema.rb
  server/db/views/feature_browse_table_rows_v06.sql
Labels: enhancement

#1090 Handle case when linked entities are nested
  server/app/models/activity.rb
Labels: bugfix

#1089 Remove rejected EIDs and Assertions from MP relations by default
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/types/entities/molecular_profile_type.rb
  server/app/models/molecular_profile.rb
Labels: bugfix

#1091 fixes minor UI issues discovered during v18 upgrades
  client/src/app/components/features/features-table/features-table.component.html
  client/src/app/layout/layout.component.html
  client/src/app/layout/layout.component.less
Labels: bugfix

#1082 upgrade angular core & all major libraries
  .github/workflows/build_frontend.yml
  client/package.json
  client/src/app/app.module.ts
  client/src/app/components/activities/activity-feed/activity-feed.component.html
  client/src/app/components/features/features-table/features-table.component.html
  client/src/app/components/layout/viewer-button/viewer-button.component.ts
  client/src/app/components/revisions/revision-list/revision-list.component.ts
  client/src/app/components/shared/empty-value/empty-value.component.html
  client/src/app/components/shared/empty-value/empty-value.component.less
  client/src/app/components/shared/empty-value/empty-value.component.ts
  client/src/app/components/shared/empty-value/empty-value.module.ts
  client/src/app/components/shared/entity-subscription-button/entity-subscription-button.component.ts
  client/src/app/components/shared/tab-navigation/tab-navigation.component.html
  client/src/app/directives/table-scroll/table-scroll.directive.ts
  client/src/app/forms/extensions/observe-query-param.extension.ts
  client/src/app/forms/states/assertion.state.ts
  client/src/app/forms/states/evidence.state.ts
  client/src/app/forms/test-pages/test-pages.view.html
  client/src/app/forms/types/acmg-code-select/acmg-code-select.type.html
  client/src/app/forms/types/clingen-code-select/clingen-code-select.type.html
  client/src/app/forms/types/disease-select/disease-select.type.html
  client/src/app/forms/types/evidence-select/evidence-manager/evidence-manager.component.ts
  client/src/app/forms/types/evidence-select/evidence-manager/evidence-manager.types.ts
  client/src/app/forms/types/evidence-select/evidence-select.type.html
  client/src/app/forms/types/evidence-select/evidence-select.type.ts
  client/src/app/forms/types/feature-select/feature-select.type.html
  client/src/app/forms/types/nccn-guideline-select/nccn-guideline-select.type.html
  client/src/app/forms/types/phenotype-select/phenotype-select.type.html
  client/src/app/forms/types/therapy-select/therapy-select.type.html
  client/src/app/forms/types/variant-select/variant-manager/variant-manager.types.ts
  client/src/app/forms/types/variant-select/variant-select.type.html
  client/src/app/forms/types/variant-type-select/variant-type-select.type.html
  client/src/app/generated/civic.apollo.ts
  client/src/app/layout/layout.component.html
  client/src/app/layout/layout.component.less
  client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.module.ts
  client/src/app/views/evidence/evidence-detail/evidence-summary/evidence-summary.module.ts
  client/src/themes/default.less
  client/yarn.lock
Labels: dependencies

#1094 post-merge codegen updates to client.apollo
  client/src/app/generated/civic.apollo.ts
Labels: housekeeping

#1097 Improve Submission Comment display when no comment exists
  client/src/app/components/activities/activity-feed/activity-feed.component.html
  client/src/app/components/comments/comment-display/comment-display.component.html
  client/src/app/components/comments/comment-display/comment-display.component.ts
  client/src/app/components/comments/comment-display/comment-display.module.ts
Labels: housekeeping

#1098 Deduplicate typeahead results when matching on an alias
  server/app/graphql/types/queries/typeahead_queries.rb
Labels: bugfix

#1099 Disease and Therapy browse table improvements
  client/src/app/components/diseases/diseases-table/diseases-table.component.html
  client/src/app/components/diseases/diseases-table/diseases-table.component.ts
  client/src/app/components/diseases/diseases-table/diseases-table.module.ts
  client/src/app/components/diseases/diseases-table/diseases-table.query.gql
  client/src/app/components/therapies/therapies-table/therapies-table.component.html
  client/src/app/components/therapies/therapies-table/therapies-table.component.ts
  client/src/app/components/therapies/therapies-table/therapies-table.module.ts
  client/src/app/components/therapies/therapies-table/therapies-table.query.gql
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/resolvers/browse_diseases.rb
  server/app/graphql/resolvers/browse_features.rb
  server/app/graphql/resolvers/browse_molecular_profiles.rb
  server/app/graphql/resolvers/browse_variants.rb
  server/app/graphql/resolvers/shared/search_helpers.rb
  server/app/graphql/resolvers/top_level_assertions.rb
  server/app/graphql/resolvers/top_level_evidence_items.rb
  server/app/graphql/resolvers/top_level_therapies.rb
  server/app/graphql/types/browse_tables/browse_disease_type.rb
  server/app/graphql/types/browse_tables/browse_therapy_type.rb
  server/app/jobs/refresh_materialized_views.rb
  server/app/models/materialized_views/therapy_browse_table_row.rb
  server/db/migrate/20240821202632_update_disease_browse_table_rows_to_version_8.rb
  server/db/migrate/20240821202933_create_therapy_browse_table_rows.rb
  server/db/schema.rb
  server/db/views/disease_browse_table_rows_v08.sql
  server/db/views/therapy_browse_table_rows_v01.sql
Labels: enhancement

#1100 Add rudimentary maintenance toggle admin utility
  client/src/assets/images/CIViC_logo_for-dark-bg_LG_v5a.png
  server/app/admin/utilities_admin.rb
  server/app/models/actions/toggle_maintenance.rb
  server/app/utilities/action_wrapper.rb
  server/app/utilities/toggle_maintenance_mode.rb
  server/public/assets/images/CIViC_logo_for-dark-bg_LG_v5a.png
  server/public/maintenance.html
Labels: housekeeping

#1101 added include_automated_events option to activities resolver
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/resolvers/activities.rb
Labels: enhancement

#1102 update to newest version of solid_errors
  server/Gemfile
  server/Gemfile.lock
  server/db/migrate/20240822154958_upgrade_solid_errors.rb
  server/db/migrate/20240822155113_solid_error_fingerprint_non_nullable.rb
  server/db/schema.rb
Labels: dependencies

#1103 Add NCIt details to Factor Variant card in MP view
  client/src/app/components/molecular-profiles/molecular-profile-factor-variant-card/molecular-profile-factor-variant-card.component.html
  client/src/app/components/molecular-profiles/molecular-profile-factor-variant-card/molecular-profile-factor-variant-card.component.ts
  client/src/app/components/variants/factor-variant-summary/factor-variant-summary.page.html
Labels: enhancement

#1104 Show org tag in revision header
  client/src/app/components/revisions/revision-list/revision-list.component.html
  client/src/app/components/revisions/revision-list/revision-list.module.ts
  client/src/app/components/revisions/revisions-list-and-filter/revisions-list-and-filter.query.gql
  client/src/app/generated/civic.apollo.ts
Labels: enhancement

#1105 Filter out sources without citations from browse view
  server/app/graphql/resolvers/browse_sources.rb
Labels: bugfix

#1106 Allow evidence and assertion tables to be filtered by status
  client/src/app/components/assertions/assertions-table/assertions-table.component.html
  client/src/app/components/assertions/assertions-table/assertions-table.component.ts
  client/src/app/components/assertions/assertions-table/assertions-table.module.ts
  client/src/app/components/evidence/evidence-table/evidence-table.component.html
  client/src/app/components/evidence/evidence-table/evidence-table.component.ts
  client/src/app/components/evidence/evidence-table/evidence-table.module.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/resolvers/top_level_assertions.rb
  server/app/graphql/resolvers/top_level_evidence_items.rb
  server/app/graphql/types/evidence_status_filter_type.rb
Labels: enhancement
