Repository griffithlab/civic-v2, pull requests merged in 2024-03, with the labels that each got.

#1006 Fix MP alias form field enable/disable logic
  client/src/app/forms/config/molecular-profile-revise/molecular-profile-revise.form.config.ts
  client/src/app/forms/config/molecular-profile-revise/molecular-profile-revise.form.ts
Labels: bugfix

#1007 Introduce Account Merge Tool
  server/app/models/actions/merge_accounts.rb
  server/app/models/notification.rb
  server/app/models/subscription.rb
Labels: housekeeping

#1004 Example Queries Wrapper around GraphiQL sandbox
  server/Gemfile
  server/Gemfile.lock
  server/app/assets/config/manifest.js
  server/app/controllers/graphiql_controller.rb
  server/app/javascript/application.js
  server/app/views/graphiql/show.html.erb
  server/config/initializers/graphiql.rb
  server/config/query_examples/accepted_evidence.yml
  server/config/query_examples/evidence_counts.yml
  server/config/query_examples/evidence_for_variant.yml
  server/config/routes.rb
Labels: new-feature

#982 upgraded angular and synchronized major libraries to v17
  client/angular.json
  client/package.json
  client/src/app/components/activities/activity-card/activity-card.module.ts
  client/src/app/components/activities/activity-feed/activity-feed.module.ts
  client/src/app/components/activities/collapsible-card/collapsible-card.module.ts
  client/src/app/layout/layout.component.html
  client/src/app/layout/layout.component.less
  client/src/app/views/pages/pages-help/pages-help.page.html
  client/yarn.lock
  server/db/schema.rb
Labels: housekeeping

#984 Upgrade to Ruby 3.3
  .github/workflows/tests.yml
  client/src/app/components/layout/viewer-button/viewer-button.component.html
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/Gemfile
  server/Gemfile.lock
  server/app/controllers/application_controller.rb
  server/app/controllers/graphql_controller.rb
  server/app/graphql/civic2_schema.rb
  server/app/graphql/loaders/association_loader.rb
  server/app/lib/google_analytics_tracer.rb
  server/app/lib/graphql_analytics_tracer.rb
  server/babel.config.js
  server/bin/rails
  server/bin/rake
  server/bin/setup
  server/config/application.rb
  server/config/boot.rb
  server/config/database.yml
  server/config/deploy/production.rb
  server/config/deploy/staging.rb
  server/config/environments/development.rb
  server/config/initializers/assets.rb
  server/config/initializers/content_security_policy.rb
  server/config/initializers/cookie_rotator.rb
  server/config/initializers/enable_yjit.rb
  server/config/initializers/filter_parameter_logging.rb
  server/config/initializers/inflections.rb
  server/config/initializers/new_framework_defaults_7_1.rb
  server/config/initializers/permissions_policy.rb
  server/config/puma/production.rb
  server/config/routes.rb
  server/db/migrate/20240118184728_add_service_name_to_active_storage_blobs.active_storage.rb
  server/db/migrate/20240118184729_create_active_storage_variant_records.active_storage.rb
  server/db/migrate/20240118184730_remove_not_null_on_active_storage_blobs_checksum.active_storage.rb
  server/db/migrate/20240130000329_create_solid_errors_tables.rb
  server/db/schema.rb
  server/lib/tasks/yarn.rake
  server/package.json
  server/test/test_helper.rb
  server/yarn.lock
Labels: housekeeping
