Repository griffithlab/civic-v2, pull requests merged in 2024-04, with the labels that each got.

#1035 fix column name
  server/app/graphql/resolvers/shared/variants.rb
Labels: ignore-for-release

#1036 Support Custom Reports and Utilities In Admin
  server/app/admin/assertions_admin.rb
  server/app/admin/evidence_items_admin.rb
  server/app/admin/features_admin.rb
  server/app/admin/organizations_admin.rb
  server/app/admin/reports_admin.rb
  server/app/admin/users_admin.rb
  server/app/admin/utilities_admin.rb
  server/app/admin/variants_admin.rb
  server/app/models/actions/merge_accounts.rb
  server/app/reports/organization_contributions.rb
  server/app/reports/report.rb
  server/app/utilities/action_wrapper.rb
  server/app/utilities/merge_accounts.rb
  server/app/views/admin/reports/index.html.erb
  server/app/views/admin/reports/result.html.erb
  server/app/views/admin/reports/show.html.erb
  server/app/views/admin/shared/_field.html.erb
  server/app/views/admin/utilities/index.html.erb
  server/app/views/admin/utilities/result.html.erb
  server/app/views/admin/utilities/show.html.erb
  server/config/environments/development.rb
  server/config/initializers/trestle.rb
Labels: new-feature

#1037 Background jobs that flag entities should use the activity, not the action
  server/app/jobs/flag_duplicate_allele_registry_ids.rb
  server/app/jobs/set_allele_registry_id_single_variant.rb
  server/app/lib/importer/disease_ontology_mirror.rb
  server/app/lib/scrapers/human_phenotype_ontology.rb
Labels: bugfix

#1038 always use the base class in search, not the inherited type
  server/app/graphql/resolvers/quicksearch.rb
Labels: bugfix

#1039 add link adaptors for variant subtypes
  server/app/lib/link_adaptors/factor_variant.rb
  server/app/lib/link_adaptors/gene_variant.rb
Labels: bugfix

#1041 Add date range filtering to activity resolver
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/resolvers/activities.rb
Labels: enhancement

#1042 Add codespell: config, workflow (to detect new) + make it find/fix some existing typos
  .codespellignore
  .codespellrc
  .github/workflows/codespell.yml
  README.md
  client/src/app/components/evidence/evidence-table/evidence-table.component.html
  client/src/app/components/therapies/my-chem-info/my-chem-info.component.html
  client/src/app/core/utilities/closeable-tag-base.ts
  client/src/app/core/utilities/enum-tooltips/get-evidence-enum-tooltip.ts
  client/src/app/forms/components/form-errors-alert/form-errors-alert.component.html
  client/src/app/forms/mixins/entity-select-field.mixin.ts
  client/src/app/forms/mixins/string-select-field.mixin.ts
  client/src/app/forms/test-pages/tags-test/tags-test.page.html
  client/src/app/forms/types/evidence-select/evidence-manager/evidence-manager.config.ts
  client/src/app/forms/types/evidence-select/evidence-manager/evidence-manager.types.ts
  client/src/app/forms/types/molecular-profile-select/mp-expression-editor/mp-expression-editor.component.ts
  client/src/app/forms/types/org-submit-button/org-submit-button.type.ts
  client/src/app/forms/types/variant-select/variant-manager/variant-manager.config.ts
  client/src/app/forms/types/variant-select/variant-manager/variant-manager.types.ts
  client/src/app/forms/wrappers/form-row/form-row.wrapper.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.page.html
  client/src/app/views/features/features-home/features-home.page.html
  client/src/app/views/releases/releases-main/releases-main.component.html
  client/src/app/views/variant-groups/variant-groups-detail/variant-groups-summary/variant-groups-summary.page.html
  client/src/main.ts
  client/src/themes/overrides/entity-page-header.overrides.less
  server/app/graphql/loaders/association_count_loader.rb
  server/app/graphql/mutations/resolve_flag.rb
  server/app/graphql/mutations/update_coi.rb
  server/app/graphql/resolvers/activities.rb
  server/app/graphql/resolvers/top_level_events.rb
  server/app/graphql/types/connections/activities_connection.rb
  server/app/graphql/types/connections/events_connection.rb
  server/app/graphql/types/connections/notifications_connection.rb
  server/app/graphql/types/entities/user_type.rb
  server/app/graphql/types/molecular_profile_display_filter_type.rb
  server/app/lib/importer/disease_ontology_mirror.rb
  server/app/models/my_chem_info.rb
  server/app/models/my_disease_info.rb
  server/app/utilities/merge_accounts.rb
  server/config/initializers/trestle.rb
Labels: enhancement

#1043 Minor test improvements
  .github/workflows/build_frontend.yml
  .github/workflows/deploy.yml
  server/app/graphql/loaders/association_count_loader.rb
  server/app/graphql/resolvers/top_level_therapies.rb
  server/config/environments/test.rb
  server/test/controllers/.keep
  server/test/controllers/links_controller_test.rb
  server/test/fixtures/feature_factors.yml
  server/test/fixtures/features.yml
  server/test/fixtures/variants.yml
  server/test/graphql/mutations/create_molecular_profile_test.rb
  server/test/test_helper.rb
Labels: housekeeping

#1044 More bugfixes to the background jobs
  server/app/jobs/flag_duplicate_allele_registry_ids.rb
  server/app/lib/importer/disease_ontology_mirror.rb
  server/app/lib/importer/sequence_ontology_mirror.rb
  server/app/lib/scrapers/human_phenotype_ontology.rb
Labels: bugfix

#1045 Don't swallow errors in development mode
  client/src/app/app.module.ts
  client/src/app/core/utilities/app-error-handler.ts
  client/src/app/core/utilities/app-reload-handler.ts
Labels: housekeeping

#1046 Fix variant menu pagination
  client/src/app/components/variants/variants-menu/variants-menu.component.ts
  client/src/app/components/variants/variants-menu/variants-menu.gql
  client/src/app/generated/civic.apollo.ts
Labels: bugfix
