Repository griffithlab/civic-v2, pull requests merged in 2025-04, with the labels that each got.

#1220 update to compatible version of sidekiq-cron
  server/Gemfile
  server/Gemfile.lock
Labels: bugfix

#1222 Fix assocation of BrowseUserTableRow to a user's organization
  server/app/graphql/types/browse_tables/browse_user_type.rb
  server/app/models/materialized_views/user_browse_table_row.rb
Labels: bugfix

#1224 Add scheduled job for generating Uniprot mapping TSV
  server/app/jobs/generate_nightly_uniprot_file.rb
  server/config/scheduled_tasks.yml
  server/db/migrate/20250416144840_add_uniprot_id.rb
  server/db/schema.rb
Labels: new-feature

#1226 Add missing significance
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  client/src/app/icons-provider.module.ts
  server/app/graphql/types/evidence_significance_type.rb
Labels: bugfix

#1229 Add MP to onset terms report
  server/app/reports/eids_with_onset_terms.rb
Labels: enhancement
