Repository griffithlab/civic-v2, pull requests merged in 2025-02, with the labels that each got.

#1185 Various fixes
  server/app/graphql/types/queries/typeahead_queries.rb
  server/app/jobs/populate_fusion_coordinates.rb
  server/app/models/variants/fusion_variant.rb
Labels: bugfix

#1186 Small fixes for permalink redirects
  server/app/lib/link_adaptors/fusion_variant.rb
  server/app/models/frontend_router.rb
Labels: bugfix

#1187 Add reports to help find disease deprecation candidates.
  server/app/reports/diseases_without_eids.rb
  server/app/reports/duplicate_disease_names.rb
  server/app/reports/duplicate_doids.rb
  server/app/reports/reports.rb
Labels: enhancement

#1175 add support for API keys including generation and revokation
  client/src/app/forms/components/form-errors-alert/form-errors-alert.component.ts
  client/src/app/forms/components/user-api-keys/user-api-keys.form.html
  client/src/app/forms/components/user-api-keys/user-api-keys.form.less
  client/src/app/forms/components/user-api-keys/user-api-keys.form.ts
  client/src/app/forms/components/user-api-keys/user-api-keys.mutation.gql
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  client/src/app/views/users/users-detail/users-detail.component.html
  client/src/app/views/users/users-detail/users-detail.component.ts
  client/src/app/views/users/users-detail/users-detail.module.ts
  server/app/controllers/concerns/authentication.rb
  server/app/graphql/mutations/generate_api_key.rb
  server/app/graphql/mutations/revoke_api_key.rb
  server/app/graphql/types/api_key_type.rb
  server/app/graphql/types/entities/user_type.rb
  server/app/graphql/types/mutation_type.rb
  server/app/models/api_key.rb
  server/app/models/constants.rb
  server/app/models/user.rb
  server/config/credentials/production.yml.enc
  server/config/environments/test.rb
  server/db/migrate/20241220161652_add_api_key.rb
  server/db/schema.rb
  server/test/controllers/token_authorization_test.rb
  server/test/graphql/mutations/generate_and_revoke_api_keys_test.rb
Labels: new-feature

#1189 Update Capistrano version to address GitHub Action failure
  server/Gemfile.lock
  server/config/deploy.rb
Labels: housekeeping

#1193 Show Organization settings now work properly in organization activity tab
  client/src/app/components/activities/activity-feed/feed-item/feed-item.component.html
  client/src/app/forms/types/evidence-select/evidence-select.type.ts
  client/src/app/views/organizations/organizations-events/organizations-events.component.html
  client/src/app/views/organizations/organizations-events/organizations-events.component.ts
Labels: bugfix
