Repository griffithlab/civic-v2, pull requests merged in 2025-03, with the labels that each got.

#1199 Fix ProteinPaint url
  client/src/app/components/genes/gene-base-summary/gene-base-summary.page.html
Labels: bugfix

#1203 Remove invalid order clause
  server/app/graphql/types/queries/typeahead_queries.rb
Labels: bugfix

#1197 Add include subgroups filter option to activity feed as well as assertion and evidence browse tables
  client/src/app/components/activities/activity-feed/activity-feed.config.ts
  client/src/app/components/activities/activity-feed/activity-feed.functions.ts
  client/src/app/components/activities/activity-feed/activity-feed.query.gql
  client/src/app/components/activities/activity-feed/activity-feed.types.ts
  client/src/app/components/activities/activity-feed/feed-filters/feed-filters.component.html
  client/src/app/components/activities/activity-feed/feed-filters/feed-filters.component.ts
  client/src/app/components/activities/activity-feed/feed-filters/feed-filters.query.gql
  client/src/app/components/assertions/assertions-table/assertions-table.component.html
  client/src/app/components/assertions/assertions-table/assertions-table.component.ts
  client/src/app/components/assertions/assertions-table/assertions-table.module.ts
  client/src/app/components/assertions/assertions-table/assertions-table.query.gql
  client/src/app/components/evidence/evidence-table/evidence-table.component.html
  client/src/app/components/evidence/evidence-table/evidence-table.component.ts
  client/src/app/components/evidence/evidence-table/evidence-table.module.ts
  client/src/app/components/evidence/evidence-table/evidence-table.query.gql
  client/src/app/components/shared/tab-navigation/tab-navigation.component.html
  client/src/app/components/shared/tab-navigation/tab-navigation.component.ts
  client/src/app/forms/types/evidence-select/evidence-manager/evidence-manager.query.gql
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  client/src/app/views/organizations/organizations-events/organizations-events.component.html
  client/src/app/views/organizations/organizations-events/organizations-events.component.ts
  client/src/app/views/organizations/organizations-members/organizations-members.component.ts
  client/src/app/views/organizations/organizations-members/organizations-members.query.gql
  server/app/graphql/resolvers/activities.rb
  server/app/graphql/resolvers/top_level_assertions.rb
  server/app/graphql/resolvers/top_level_evidence_items.rb
  server/app/graphql/resolvers/top_level_users.rb
  server/app/graphql/types/connections/activities_connection.rb
  server/app/graphql/types/organization_filter_type.rb
Labels: enhancement

#1202 Submitting EIDs and Assertions should fail early if the entities would be invalid
  server/app/models/activities/base.rb
  server/app/models/activities/submit_assertion.rb
  server/app/models/activities/submit_evidence_item.rb
Labels: bugfix

#1212 Add hasLinkedEvidence filter to therapies endpoint
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/resolvers/top_level_therapies.rb
Labels: enhancement

#1217 Add banner indicating when we are in a non-production environment
  client/src/app/app.component.html
  client/src/app/app.module.ts
  client/src/app/components/app/environment-banner/environment-banner.component.html
  client/src/app/components/app/environment-banner/environment-banner.component.less
  client/src/app/components/app/environment-banner/environment-banner.component.ts
  client/src/environments/environment.prod.ts
  client/src/environments/environment.ts
  server/app/controllers/static_controller.rb
  server/config/initializers/environment_banner.rb
Labels: housekeeping

#1214 Require a comment when rejecting an EID or AID
  client/src/app/components/activities/activity-feed/activity-feed.config.ts
  client/src/app/components/activities/activity-feed/feed-item-details/moderate-assertion/moderate-assertion-activity.component.html
  client/src/app/components/activities/activity-feed/feed-item-details/moderate-assertion/moderate-assertion-activity.component.less
  client/src/app/components/activities/activity-feed/feed-item-details/moderate-assertion/moderate-assertion-activity.component.ts
  client/src/app/components/activities/activity-feed/feed-item-details/moderate-assertion/moderate-assertion-activity.query.gql
  client/src/app/components/activities/activity-feed/feed-item-details/moderate-evidence/moderate-evidence-activity.component.html
  client/src/app/components/activities/activity-feed/feed-item-details/moderate-evidence/moderate-evidence-activity.component.less
  client/src/app/components/activities/activity-feed/feed-item-details/moderate-evidence/moderate-evidence-activity.component.ts
  client/src/app/components/activities/activity-feed/feed-item-details/moderate-evidence/moderate-evidence-activity.query.gql
  client/src/app/components/shared/moderate-entity-buttons/moderate-entity-buttons.component.html
  client/src/app/components/shared/moderate-entity-buttons/moderate-entity-buttons.component.ts
  client/src/app/components/shared/moderate-entity-buttons/moderate-entity-buttons.module.ts
  client/src/app/components/shared/revert-entity-button/revert-entity-button.component.html
  client/src/app/components/shared/revert-entity-button/revert-entity-button.component.less
  client/src/app/components/shared/revert-entity-button/revert-entity-button.component.ts
  client/src/app/components/shared/revert-entity-button/revert-entity-button.module.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/mutations/moderate_assertion.rb
  server/app/graphql/mutations/moderate_evidence_item.rb
  server/app/models/activities/moderate_assertion.rb
  server/app/models/activities/moderate_evidence_item.rb
Labels: enhancement

#1218 Reintroduce "Mixed" variant origin value
  client/src/app/core/utilities/enum-tooltips/get-evidence-enum-tooltip.ts
  client/src/app/forms/types/origin-select/origin-select.type.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/civic.icons.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  client/src/app/icons-provider.module.ts
  client/src/assets/icons/attribute/mixed-outline.svg
  server/app/graphql/types/variant_origin_type.rb
  server/app/models/constants.rb
Labels: enhancement
