Repository griffithlab/civic-v2, pull requests merged in 2025-01, with the labels that each got.

#1169 port gene summaries tsv exporter to feature exporter
  server/app/jobs/generate_tsvs.rb
  server/app/jobs/upload_tsvs_to_aws.rb
  server/app/tsv_formatters/feature_tsv_formatter.rb
  server/app/tsv_formatters/gene_tsv_formatter.rb
  server/app/tsv_formatters/variant_tsv_formatter.rb
Labels: enhancement

#1177 Rename gene tsv to feature tsv on the downloads page
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  client/src/app/views/releases/releases-main/releases-list.query.gql
  client/src/app/views/releases/releases-main/releases-main.component.html
  server/app/graphql/types/data_release_type.rb
  server/app/graphql/types/queries/data_release_query.rb
Labels: housekeeping

#1178 When revising a fusion variant, allow for optional exon coordinates
  client/src/app/forms/config/fusion-variant-revise/fusion-variant-revise.form.config.ts
  server/app/graphql/mutations/suggest_fusion_variant_revision.rb
Labels: bugfix

#1181 rank typeahead results by length of matched name
  server/app/graphql/types/queries/typeahead_queries.rb
Labels: bugfix

#1180 Update short links to allow doid, ncit_id, and hpo_id
  server/app/lib/link_adaptors/phenotype.rb
  server/app/models/frontend_router.rb
Labels: enhancement
