Repository griffithlab/civic-v2, pull requests merged in 2025-05, with the labels that each got.

#1124 Update feature uniqueness validation to take into account revision context
  server/app/models/feature.rb
Labels: bugfix

#1234 Port revision activity subject logic to rejection activity
  server/app/models/activities/reject_revisions.rb
Labels: bugfix

#1237 Endorsements bug fixes, code improvements, cleanup
  client/src/app/components/assertions/assertions-popover/assertion-popover.component.html
  client/src/app/components/assertions/assertions-popover/assertions-popover.module.ts
  client/src/app/components/endorsements/endorsable/endorsable.component.html
  client/src/app/components/endorsements/endorsable/endorsable.component.less
  client/src/app/components/endorsements/endorsable/endorsable.component.ts
  client/src/app/components/endorsements/endorse-assertion-button/endorse-assertion-button.component.html
  client/src/app/components/endorsements/endorsement-display/endorsement-display.component.html
  client/src/app/components/endorsements/endorsement-display/endorsement-display.component.ts
  client/src/app/components/endorsements/endorsement-display/endorsement-display.module.ts
  client/src/app/components/endorsements/endorsement-item/endorsement-item.component.html
  client/src/app/components/endorsements/endorsement-item/endorsement-item.component.less
  client/src/app/components/endorsements/endorsement-item/endorsement-item.component.ts
  client/src/app/components/endorsements/endorsement-list/endorsement-list.component.html
  client/src/app/components/endorsements/endorsement-list/endorsement-list.component.less
  client/src/app/components/endorsements/endorsement-list/endorsement-list.component.ts
  client/src/app/components/endorsements/endorsement-list/endorsement-list.module.ts
  client/src/app/components/endorsements/endorsement-notification/endorsement-notification.component.html
  client/src/app/components/endorsements/endorsement-notification/endorsement-notification.component.less
  client/src/app/components/endorsements/endorsement-notification/endorsement-notification.component.ts
  client/src/app/components/endorsements/endorsement-pipes/can-create-endorsement.pipe.ts
  client/src/app/components/endorsements/endorsement-pipes/can-revoke-endorsement.pipe.ts
  client/src/app/components/endorsements/endorsement-pipes/current-org-can-endorse.pipe.ts
  client/src/app/components/endorsements/endorsement-pipes/endorsement-action-tooltip.pipe.ts
  client/src/app/components/endorsements/endorsement-pipes/endorsement.functions.ts
  client/src/app/core/pipes/can-create-endorsement.pipe.ts
  client/src/app/core/pipes/can-endorse-assertion.pipe.ts
  client/src/app/core/pipes/can-revoke-assertion.pipe.ts
  client/src/app/core/pipes/pipes.module.ts
  client/src/app/views/assertions/assertions-detail/assertions-detail.module.ts
  client/src/app/views/assertions/assertions-detail/assertions-detail.view.html
  client/src/app/views/assertions/assertions-detail/assertions-detail.view.ts
  client/src/app/views/assertions/assertions-detail/assertions-endorsements/assertions-endorsements.module.ts
  client/src/app/views/assertions/assertions-detail/assertions-endorsements/assertions-endorsements.page.ts
  client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.module.ts
  client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.page.html
Labels: bugfix

#1238 Make MP and Variant TSV queries consistent with each other
  server/app/tsv_formatters/molecular_profile_tsv_formatter.rb
  server/app/tsv_formatters/variant_tsv_formatter.rb
Labels: bugfix

#1232 Enable both a browseOrganizations and organizations query
  client/src/app/components/activities/activity-feed/feed-filters/org-filter-select/org-filter-select.component.ts
  client/src/app/components/activities/activity-feed/feed-filters/org-filter-select/org-filter-select.query.gql
  client/src/app/components/organizations/organizations-table/organizations-table.component.ts
  client/src/app/components/organizations/organizations-table/organizations-table.query.gql
  client/src/app/generated/civic.apollo-helpers.ts
  client/src/app/generated/civic.apollo.ts
  client/src/app/generated/server.model.graphql
  client/src/app/generated/server.schema.json
  server/app/graphql/resolvers/browse_organizations.rb
  server/app/graphql/resolvers/top_level_organizations.rb
  server/app/graphql/types/query_type.rb
Labels: enhancement

#1233 Prevent deprecation of Variants/MPs if the MP is involved in an open revision
  server/app/graphql/mutations/deprecate_complex_molecular_profile.rb
  server/app/graphql/mutations/deprecate_variant.rb
  server/app/models/actions/deprecate_variant.rb
Labels: enhancement

#1242 Specify array of amp tiers explicitly to enforce ordering in select
  client/src/app/forms/types/amp-category-select/amp-category-select.type.ts
Labels: housekeeping

#1243 Improve handling of duplicate revisions
  server/app/models/actions/suggest_revision_set.rb
  server/app/models/activities/suggest_revision_set.rb
Labels: bugfix
